### ISSUE TITLE
Call site calculation fails when importing an esm'ed package that imports sequelize internally

### ISSUE THREAD

**Issue by charandas** [dougwilson/nodejs-depd#28]
@dougwilson As promised in #27 here is the [repro](https://github.com/charandas/depd-repro-jest) of the issue I am having. Use the `with-esm` branch to see the issue.

The `without-esm` branch is fine with importing sequelize, so maybe not worth seeing.

I tested with couple Node versions, v8.9.0 and v10.7.0, so I doubt the version matters there.

**Comment by charandas** [comment]
Just added a readme to the repo. Let me know if anything about the setup is unclear.

**Comment by dougwilson** [comment]
Thanks, I will take a look soon. Can you please post the exact error with it's full stack trace that is being thrown?

**Comment by charandas** [comment]
I remember seeing longer stacktraces couple weeks ago, which go to common sequelize depd file, but can no longer create a long stacktrace. Here is what you will see with the repo:

```
    TypeError: callSite.getFileName is not a function

      at callSiteLocation (packages/some-esm-package/node_modules/depd/index.js:252:23)
```

**Comment by charandas** [comment]
Also, the same issue happens whether you use `ts-jest` or `jest`. For using latter, one has to remove the `transform` portion from package.json (`"^.+\\.(ts|tsx)$": "ts-jest"`), as well as change the `spec.ts` file to `spec.js` (stripping it of ES6 imports).

I created the repro with `ts-jest` since that is my current use-case.

**Comment by dougwilson** [comment]
So thanks for the repo. This is a Node.js bug: https://github.com/nodejs/node/issues/21270 and since `esm` lib runs code inside a `vm` context it triggers the bug.

**Comment by dougwilson** [comment]
Sorry, didn't mean to click comment + close.

**Comment by dougwilson** [comment]
I'm trying to see if it's possible there is a user-land solution but I cannot find one, and it may not be possible to fix without Node.js core involvement. I may be able to detect this brokenness at runtime and load the browser version (which is basically a complete no-op) instead. This would make your code work, though you'd get no deprecation warnings from any module in return.

**Comment by dougwilson** [comment]
Unfortunately since it seems like the `esm` lib is minified on install and does not provide a source map, it's pretty much impossible to debug. To move forward and get a test I need to figure out how to invoke `vm` in the same way `esm` is doing so I can add a test to the test suite (and also understand it better to know if there is actually a work-around or not).

**Comment by charandas** [comment]
May wanna involve @jdalton for a quick answer. Hope this doesn't count as spam.

**Comment by jdalton** [comment]
Thanks for the ping and the repro. I'll dig in soon.

**Comment by jdalton** [comment]
**Update:**

It's related to [this](https://github.com/nodejs/node/issues/21270) issue (v8 patch [here](https://chromium-review.googlesource.com/c/v8/v8/+/1113438))

Simple repro with nvm to version switch. 

Try Node 6.x:

```js
s=new vm.Script('var o={};Error.prepareStackTrace=(o,s)=>s;Error.captureStackTrace(o);o.stack')
s.runInNewContext(vm.createContext(global)) // an array [CallSite {},...]
```
In Node 8+
```
s=new vm.Script('var o={};Error.prepareStackTrace=(o,s)=>s;Error.captureStackTrace(o);o.stack')
s.runInNewContext(vm.createContext(global)) // a string "'Error\n    at evalmachine.<anonymous>..."
```

The reason `esm` is running into this is we try to run in a `jest` specific context which causes the stack to not be properly prepared by `depd` resulting in a string instead of the expected array.

I'll see what we can do from our end.

**Comment by jdalton** [comment]
**Update:**

Patched https://github.com/standard-things/esm/commit/c464c35b441a8cdccd582b8e6a0f4483e16cc84d.

**Comment by charandas** [comment]
Thanks to you both.

**Comment by charandas** [comment]
@jdalton could that patched package be released soon?

**Comment by jdalton** [comment]
@charandas Yes, it'll be released this by this afternoon.

**Comment by jdalton** [comment]
**Update:**

[v3.0.77](https://github.com/standard-things/esm/releases/tag/3.0.77) is released :tada:
