### ISSUE TITLE
callSite.getFileName() is not Function

### ISSUE THREAD

**Issue by GuoSirius** [dougwilson/nodejs-depd#47]
![image](https://user-images.githubusercontent.com/48358523/148884480-900547b6-5da6-442a-b6e8-439c4924b391.png)
![image](https://user-images.githubusercontent.com/48358523/148884503-ceb1d3de-bf2b-406e-9765-126171c1b109.png)

**Comment by dougwilson** [comment]
Hi, and sorry you are having trouble. What version of Node.js are you getting this error with?

**Comment by muwoo** [comment]
@dougwilson I have the same problem. my node version is 14.6. I printed out the value of the `callSite` which is an empty object: `{}`. I am looking forward to your reply. Thanks！

**Comment by dougwilson** [comment]
Thanks. I just played around on 14.6 without issue. Can you provide instructions for how you set up this where there error happens so I can replicate it?

**Comment by GuoSirius** [comment]
node 14.17.5
electron 13.6.6
camo 0.12.4

you can use vue-cli to create electron project and run .

**Comment by dougwilson** [comment]
Thank you @GuoSirius i just tried that and was unable to reproduce. If you can procide more derailed instructions, I can reopen.
